### ISSUE TITLE
Putting binaries inside the source file

### ISSUE THREAD

**Issue by olivier-stasse** [humanoid-path-planner/hpp-spline#2]
https://github.com/stonneau/spline/blob/ca4c028ba881b8e47739dc148745a1d456b5d2d9/CMakeLists.txt#L13
I do not believe this is a good idea to put the binary inside the source directory...

**Comment by stonneau** [comment]
Indeed, probably not... This is obviously a mistake in the configuration file. 
I'll fix this asap
